### ISSUE TITLE
Error starting chrome

### ISSUE THREAD

**Issue by screeny05** [trion-development/docker-ng-cli-karma#16]
Using the current [latest tag](https://hub.docker.com/layers/trion/ng-cli-karma/latest/images/sha256-70bc7da4e052e3fa3a5e5c36093e7955f57558d6f1f9c1787972fbead1da9e9d?context=explore) we experience issues when trying to start chrome in the docker container.

Here's the log we get:

```
28 10 2022 09:17:11.306:INFO [karma-server]: Karma v5.2.3 server started at http://localhost:9876/
28 10 2022 09:17:11.307:INFO [launcher]: Launching browsers ChromeHeadlessCustom with concurrency unlimited
28 10 2022 09:17:11.311:INFO [launcher]: Starting browser ChromeHeadless
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/builds/gries-deco-company/web/storefront/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/builds/gries-deco-company/web/storefront/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash (/builds/gries-deco-company/web/storefront/node_modules/webpack/node_modules/webpack-sources/lib/RawSource.js:64:8)
    at NormalModule._initBuildHash (/builds/gries-deco-company/web/storefront/node_modules/webpack/lib/NormalModule.js:870:17)
    at handleParseResult (/builds/gries-deco-company/web/storefront/node_modules/webpack/lib/NormalModule.js:936:10)
    at /builds/gries-deco-company/web/storefront/node_modules/webpack/lib/NormalModule.js:1028:4
    at processResult (/builds/gries-deco-company/web/storefront/node_modules/webpack/lib/NormalModule.js:745:11)
    at /builds/gries-deco-company/web/storefront/node_modules/webpack/lib/NormalModule.js:809:5
28 10 2022 09:17:15.612:ERROR [karma-server]: UnhandledRejection: callback(): The callback was already called.
28 10 2022 09:17:15.620:ERROR [karma-server]: Error: callback(): The callback was already called.
    at context.callback (/builds/gries-deco-company/web/storefront/node_modules/loader-runner/lib/LoaderRunner.js:119:10)
    at Object.done (/builds/gries-deco-company/web/storefront/node_modules/@jsdevtools/coverage-istanbul-loader/lib/index.js:57:14)
    at Instrumenter.instrument (/builds/gries-deco-company/web/storefront/node_modules/istanbul-lib-instrument/dist/instrumenter.js:157:7)
    at Object.default_1 (/builds/gries-deco-company/web/storefront/node_modules/@jsdevtools/coverage-istanbul-loader/lib/index.js:49:18)
    at LOADER_EXECUTION (/builds/gries-deco-company/web/storefront/node_modules/loader-runner/lib/LoaderRunner.js:132:14)
    at runSyncOrAsync (/builds/gries-deco-company/web/storefront/node_modules/loader-runner/lib/LoaderRunner.js:133:4)
    at iterateNormalLoaders (/builds/gries-deco-company/web/storefront/node_modules/loader-runner/lib/LoaderRunner.js:250:2)
    at iterateNormalLoaders (/builds/gries-deco-company/web/storefront/node_modules/loader-runner/lib/LoaderRunner.js:239:10)
    at /builds/gries-deco-company/web/storefront/node_modules/loader-runner/lib/LoaderRunner.js:254:3
    at context.callback (/builds/gries-deco-company/web/storefront/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
28 10 2022 09:17:15.621:ERROR [karma-server]: UnhandledRejection: callback(): The callback was already called.
28 10 2022 09:17:15.621:ERROR [karma-server]: Error: callback(): The callback was already called.
    at context.callback (/builds/gries-deco-company/web/storefront/node_modules/loader-runner/lib/LoaderRunner.js:119:10)
    at Object.done (/builds/gries-deco-company/web/storefront/node_modules/@jsdevtools/coverage-istanbul-loader/lib/index.js:57:14)
    at Instrumenter.instrument (/builds/gries-deco-company/web/storefront/node_modules/istanbul-lib-instrument/dist/instrumenter.js:157:7)
    at Object.default_1 (/builds/gries-deco-company/web/storefront/node_modules/@jsdevtools/coverage-istanbul-loader/lib/index.js:49:18)
    at LOADER_EXECUTION (/builds/gries-deco-company/web/storefront/node_modules/loader-runner/lib/LoaderRunner.js:132:14)
    at runSyncOrAsync (/builds/gries-deco-company/web/storefront/node_modules/loader-runner/lib/LoaderRunner.js:133:4)
    at iterateNormalLoaders (/builds/gries-deco-company/web/storefront/node_modules/loader-runner/lib/LoaderRunner.js:250:2)
    at iterateNormalLoaders (/builds/gries-deco-company/web/storefront/node_modules/loader-runner/lib/LoaderRunner.js:239:10)
    at /builds/gries-deco-company/web/storefront/node_modules/loader-runner/lib/LoaderRunner.js:254:3
    at context.callback (/builds/gries-deco-company/web/storefront/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
```

This issue does not appear when using 14.2.6.

**Comment by everflux** [comment]
It seems you use a custom chrome configuration.
Could you try with the provided chrome configuration/wrapper?
